project_id = "incrfwanfvnrebztvffd"

[auth]
site_url = "https://vanessalimashoes.com.br"
additional_redirect_urls = ["https://vanessalimashoes.com.br/auth", "https://www.vanessalimashoes.com.br/auth", "http://localhost:8080/auth", "http://localhost:5173/auth"]
enable_signup = false

[functions.cron-cleanup-logs]
verify_jwt = false

[functions.seo-sitemap]
verify_jwt = false

[functions.seo-robots]
verify_jwt = false

[functions.checkout-stripe-webhook]
verify_jwt = false

[functions.seo-generate]
verify_jwt = false
