// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://sojrvsbqkrbxoymlwtii.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvanJ2c2Jxa3JieG95bWx3dGlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2MzU1NjcsImV4cCI6MjA4NjIxMTU2N30.ARt81W_JkVxrorq3xGj0U2HntPzewGZ5b2r9Gd-Fjjg';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});